vim.lsp.enable('lua_ls')
vim.lsp.enable('pyright')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('clangd')
vim.lsp.enable('svls')
vim.lsp.enable('asm_lsp')
vim.lsp.enable('jdtls')

-- Web dev
vim.lsp.enable('ts_ls')
vim.lsp.enable('eslint')
vim.lsp.enable('tailwindcss')
vim.lsp.enable('emmet_language_server')
vim.lsp.enable('html')
vim.lsp.enable('cssls')
